name: Deploy to GitHub Pages

on:
  # Se ejecuta cuando hay push a la rama main
  push:
    branches: [ main ]

  # Permite ejecutar manualmente desde la interfaz de GitHub
  workflow_dispatch:

# Permisos necesarios para hacer push a main
permissions:
  contents: write

jobs:
  # Job para construir y desplegar la aplicación
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Construir para producción
        run: npm run build

      - name: Desplegar a main branch
        run: |
          # Configurar git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Cambiar a main branch
          git checkout main || git checkout -b main

          # Limpiar contenido actual (excepto .git)
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

          # Copiar archivos del build
          cp -r dist/* .

          # Agregar y hacer commit
          git add .
          git commit -m "Deploy: $(date)" || exit 0

          # Push a main
          git push origin main
