name: Deploy to GitHub Pages

on:
  # Se ejecuta cuando hay push a la rama github-pages
  push:
    branches: [ github-pages ]
  
  # Permite ejecutar manualmente desde la interfaz de GitHub
  workflow_dispatch:

# Permisos necesarios para desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Solo permite un despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job para construir la aplicación
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Instalar dependencias
        run: npm ci
        
      - name: Construir para producción
        run: npm run build
        
      - name: Configurar Pages
        uses: actions/configure-pages@v4
        
      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Job para desplegar en GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
